project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Remote sensing learning Diary"
  author: "Zhengyong Liu"
  date: "1/25/2024"
  chapters:
    - index.qmd
    - Week_1.qmd
    - Week_2.qmd
    - Week_3.qmd
    - Week_4.qmd
    - Week_6.qmd
    - Week_7.qmd
    - Week_8.qmd
    - Week_9.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

