---
title: "Week_1"
bibliography: references.bib
---

## **Knowledge gain From the Lecture**

::: {style="text-align: justify;"}
This week's learning journey into the realm of remote sensing, unveiling the intricate world of electromagnetic waves and their interactions with Earth's surface. Remote sensing, as I've learned, involves acquiring information about objects or areas from a distance, typically from aircraft or satellites, and is a vital tool in understanding our planet.
:::

### **Foundational Concepts of Remote Sensing**

::: {style="text-align: justify;"}
One of the foundational concepts we explored was the difference between passive and active remote sensing. Passive remote sensing relies on natural energy, usually from the sun, whereas active remote sensing systems emit their own energy to illuminate objects. This distinction is crucial for understanding the varied applications of remote sensing technologies like LiDAR, radar, and satellite imagery in observing earth's landscapes, urban areas, and atmospheric conditions.
:::

### **Electromagnetic Waves: Core of Remote Sensing**

::: {style="text-align: justify;"}
Much of our learning focused on electromagnetic waves, the heart of remote sensing. These waves, a form of energy that propagates through electric and magnetic fields, are the backbone of how remote sensors collect data. Understanding the wavelength equation and the speed of light provides a basis for understanding how different sensors capture different aspects of the Earth's surface.
:::

### **Interactions with Earth's Surface**

::: {style="text-align: justify;"}
We have looked at the complexities of how electromagnetic radiation (EMR) interacts with the Earth's surface. This interaction is not straightforward because EMR can be absorbed, transmitted or scattered by the surface and atmosphere. Scattering, in particular, explains phenomena such as the blue colour of the sky or the blackness of the lunar sky due to the absence of an atmosphere. This concept has far-reaching implications for environmental monitoring and the study of planetary bodies.
:::

### **Synthetic Aperture Radar (SAR) and its Applications**

::: {style="text-align: justify;"}
The Synthetic Aperture Radar (SAR) was another fascinating topic. SAR's ability to 'see through clouds' using longer wavelengths is revolutionary, offering a consistent observation capability irrespective of weather conditions. This technology's potential in areas like topography, vegetation analysis, and urban planning is immense, showcasing how advanced remote sensing techniques can overcome environmental challenges

The study of SAR data also introduced us to the concept of polarization, a property of electromagnetic waves that describes their oscillation direction. This property is crucial for understanding how radar signals interact with different surface properties and is instrumental in enhancing the efficiency and bandwidth of communications.
:::

### **Technical Insights and Data Formats in Remote Sensing**

::: {style="text-align: justify;"}
On the technical side, we learned about the different data formats used in remote sensing, such as GeoTIFF, and the importance of resolutions - spatial, spectral, temporal and radiometric. These resolutions define the quality and type of data acquired, and influence how effectively we can interpret and use the data for various applications such as land cover mapping and environmental monitoring.

In the literature, these concepts are used to analyse environmental change, urban development and geological features. Understanding remote sensing data and their interpretation is essential for researchers and policy makers to make informed decisions. 
:::

## Reflecting From the Practical

### Using of SNAP

I am still trying to figure out how to fix the bug with snap while using the MacOS.

## Reflecting From the Lecture

::: {style="text-align: justify;"}
Reflecting on the week's learning, I am struck by the profound impact that remote sensing has on our understanding of the world. The ability to observe and analyse our planet from a distance provides a unique perspective that is not possible through ground-based observations alone. It literally allows us to see the bigger picture, providing a comprehensive understanding of large-scale environmental patterns, urban development and even climate change.

Remote sensing is interdisciplinary in nature. It's not just a tool for geographers or environmental scientists; it integrates physics, engineering, environmental science and even policy-making. This integration demonstrates the collaborative effort required to address complex global issues. For example, remote sensing data can inform policies on urban planning, agricultural practices and disaster management, making it a critical tool for sustainable development.

Another aspect is the rapid evolution of remote sensing technology. With innovations such as high-resolution imagery and real-time data analysis, the potential applications of this technology are expanding at an incredible rate.
:::

## Reference

'Remote Sensing - NASA', n.d. <https://www.nasa.gov/directorates/somd/space-communications-navigation-program/remote-sensing/>.

'Types Of Remote Sensing: Devices And Their Applications', 18 November 2020. <https://eos.com/blog/types-of-remote-sensing/>.
